#perform-alice
#uid=c6f0edda-17f1-4e26-84ff-c3c792e0705f
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3T0RNeE16ZzVPREFlRncweU1ERXlNVGd4TnpVeE16aGFGdzB6TURFeU1UWXhOelV4TXpoYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3T0RNeE16ZzVPREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkhxYzVBeHFpUEZZbEJrZVhqVE5RWE5PSDErVExYR0dNVlYvanlCYldRdXAKV1RPM1ZaYmRCNis5M2l4U2hOVHRWWUFJcWkyREhtbS9yRlVzYTREc0IwYWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNLLzBtZzhBZ2FhCkZzc2R2c0ZuNDNVN2pqUi8wdm51WWhoTjVlbGk2N3VXQWlCTEJZQWR1Mmg3akFDNFgzeGVkM0xCN1FMdEVlK0YKYnZmYU9PbjFZYUJQYUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://34.70.105.10
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 82243286d6e868e0fe43b8d0c59d0ee0
    username: admin
